[build]
  command = "yarn deploy"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  NEXT_PUBLIC_CHEC_PUBLIC_KEY = "pk_4467004b8a3d78ac5344cbddb63128bd52027be1b4b35"
